sudo: required
services:
  - docker

before_install:
  - docker build -t ashokalex/react-test -f ./client/Dockerfile.dev ./client




after_sucess:
  - docker build -t ashokalex/multi-client ./client
  - docker build -t ashokalex/multi-nginx ./nginx
  - docker build -t ashokalex/multi-server ./server
  - docker build -t ashokalex/multi-worker ./worker
  # Log in to the docker CLI 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ashokalex/multi-client
  - docker push ashokalex/multi-nginx
  - docker push ashokalex/multi-server
  - docker push ashokalex/multi-worker



